# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9742a2b69ca666c616a35bbd6ca332592783d065ccc2d1ed119045e24f8b523ffea9f11ff05701b0b15afa7e481b6af41b9b1fc10b10023b353e2128c6a36549

test:
  secret_key_base: 6de7b2a88398030c57274bf98e8f33cf276de4fd20754345fe6f9c02f92b6ae2efeedaf2facb336f7a5b9744d331a6306c6c3938faf30c5166e73f9ce5a12f67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
